config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, path: 'admin', skip: :registrations

  devise_for :users

  get 'buildings/index'


 #get 'buildings/index'

  namespace :admin do
    resources :buildings do
      resources :rooms
    end
    resources :lessons
    resources :courses
  end

  get 'admin' => 'admin/building#index'



  resources :buildings do
    resources :rooms, only: [:index, :new, :create, :edit, :update, :destroy, :show] do

      resources :lessons
    end

  end





  #root 'buildings#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/building.rb
class Building < ApplicationRecord
  has_many :rooms, dependent: :destroy
  validates :title, presence: true,
            length: { minimum: 5 }
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :teacher_assignments
  has_many :teachers, through: :teacher_assignments

  has_many :student_assignments
  has_many :students, through: :student_assignments

  has_many :lessons
  validates :title, presence: true

  extend Enumerize

  enumerize :language, in: { czech: 1, english: 2}, default: :czech
  enumerize :study_type, in: %w(full_time part_time), predicates: true

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :room
  belongs_to :teacher
  belongs_to :course

  validates :start_at, presence: true
  validates :end_at, presence: true

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :building, :foreign_key => 'building_id'
  has_many :lessons
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :student_assignments
  has_many :courses, through: :student_assignments

  extend Enumerize

  enumerize :study_type, in: %w(full_time part_time), predicates: true

  validates :first_name, presence: true,
            length: { maximum: 20 }

  validates :last_name, presence: true,
            length: { maximum: 20 }
end

app/models/student_assignment.rb
class StudentAssignment < ApplicationRecord
  belongs_to :course
  belongs_to :student
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :teacher_assignments
  has_many :courses, through: :teacher_assignments
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/teacher_assignment.rb
class TeacherAssignment < ApplicationRecord
  belongs_to :teacher
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < Admin::AdminController
  before_action :set_admin_room, only: [:show, :edit, :update, :destroy]

  # GET /admin/rooms
  # GET /admin/rooms.json
  def index
    @admin_rooms = Room.all
  end

  # GET /admin/rooms/1
  # GET /admin/rooms/1.json
  def show
  end

  # GET /admin/rooms/new
  def new
    @admin_room = Room.new
  end

  # GET /admin/rooms/1/edit
  def edit
  end

  # POST /admin/rooms
  # POST /admin/rooms.json
  def create
    @admin_room = Room.new(admin_room_params)

    respond_to do |format|
      if @admin_room.save
        format.html { redirect_to [:admin, @admin_room], notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @admin_room }
      else
        format.html { render :new }
        format.json { render json: @admin_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/rooms/1
  # PATCH/PUT /admin/rooms/1.json
  def update
    respond_to do |format|
      if @admin_room.update(admin_room_params)
        format.html { redirect_to [:admin, @admin_room], notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_room }
      else
        format.html { render :edit }
        format.json { render json: @admin_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/rooms/1
  # DELETE /admin/rooms/1.json
  def destroy
    @admin_room.destroy
    respond_to do |format|
      format.html { redirect_to [:admin, admin_rooms_url], notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_room
      @admin_room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
  def room_params
    params.require(:room).permit(:title, :code, :building_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  #before_action :authenticate_user!
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController



  def index
    @buildings = Building.all
  end

  def show
    @building = Building.find(params[:id])
  end

  def new
    @building = Building.new
  end

  def edit
    @building = Building.find(params[:id])
  end

  def create
    @building = Building.new(building_params)

    if @building.save
      redirect_to @building
    else
      render 'new'
    end

  end


  def update
    @building = Building.find(params[:id])

    if @building.update(building_params)
      redirect_to @building
    else
      render 'edit'
    end
  end


  def destroy
    @building = Building.find(params[:id])

    @building.destroy

    redirect_to buildings_path
  end

  private
  def building_params
    params.require(:building).permit(:title, :code)
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show ]


  def index
    @courses = Course.all
  end


  def show
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :code, :study_type, :language)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  before_action :set_lesson, only: [:show]
  before_action :set_room


  def index
    @lessons = Lesson.all
  end

  def new
    @lesson = Lesson.new
  end


  def show
  end

  private
  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def lesson_params
    params.require(:lesson).permit(:start_at, :end_at, :duration)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :set_building
  before_action :set_room, only: [:show ]

  def create
    @building = Building.find(params[:building_id])
    @room = @building.rooms.create(room_params)
    redirect_to building_path(@building)
  end

  def new
    @room = Room.new(building_id: @building.id)
  end

  def show

  end


  def destroy
    @building = Building.find(params[:building_id])
    @room = @building.rooms.find(params[:id])
    @room.destroy
    redirect_to building_path(@building)
  end



  private
  def set_building
    @building = Building.find(params[:building_id])
  end

  def set_room
    @room = Room.find(params[:id])
  end



  def room_params
    params.require(:room).permit(:title, :code, :building_id)
  end
end

app/helpers/admin/courses_helper.rb
module Admin::CoursesHelper
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/admin/rooms/_form.html.erb
<%= simple_form_for(@admin_room) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/rooms/edit.html.erb
<h1>Editing Admin Room</h1>

<%= render 'form', admin_room: @admin_room %>

<%= link_to 'Show', @admin_room %> |
<%= link_to 'Back', admin_rooms_path %>

app/views/admin/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Rooms</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_rooms.each do |admin_room| %>
      <tr>
        <td><%= link_to 'Show', [:admin, admin_room] %></td>
        <td><%= link_to 'Edit', edit_admin_room_path(admin_room) %></td>
        <td><%= link_to 'Destroy', [:admin, admin_room], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Room', new_admin_room_path %>

app/views/admin/rooms/new.html.erb
<h1>New Admin Room</h1>

<%= render 'form', admin_room: @admin_room %>

<%= link_to 'Back', admin_rooms_path %>

app/views/admin/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_room_path(@admin_room) %> |
<%= link_to 'Back', admin_rooms_path %>

app/views/rooms/_form.html.erb
<%= simple_form_for([@building, @room] ) do |f| %>
    <%= f.input :title %>
    <%= f.input :code %>
    <%= f.button :submit %>
<% end %>

app/views/rooms/_room.html.erb
<p>
  <strong>Title:</strong>
  <%= room.title %>
</p>

<p>
  <strong>Code:</strong>
  <%= room.code %>
</p>
<p>
  <strong>Room id</strong>
<%= room.id %>
</p>




<p>
  <%= link_to "Show room #{room.title}", [room.building, room] %>
</p>
<p>
  <%= link_to 'Destroy Room', [room.building, room],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

app/views/rooms/_rooms.html.erb
<p>
  <strong>Title:</strong>
  <%= room.title %>
</p>

<p>
  <strong>Code:</strong>
  <%= room.code %>
</p>

<p>
  <%= link_to 'Destroy Room', [room.building, room],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

app/views/rooms/new.html.erb
<h1>New Rooms</h1>

<%= render 'form' %>

<%= link_to 'Back', building_path(params[:building_id]) %>

app/views/rooms/show.html.erb
<div class="container-fluid">
  <p>
    <strong>Title:</strong>
    <%= @room.title %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= @room.code %>
  </p>



  <%= link_to 'Lessons', building_room_lessons_path(room_id: @room.id) %>
|
  <%= link_to 'New lesson', new_building_room_lesson_path(room_id: @room.id) %>

  <br />
  <br />



  <%= link_to 'Edit', edit_building_path(@building) %> |
  <%= link_to 'Delete',
              building_path(@building),
              method: :delete,
              data: { confirm: 'Jsi si jistý?' } %>  |
  <%= link_to 'Back', building_path(params[:building_id]) %>

</div>