config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, path: 'admin', skip: :registrations

  devise_for :users

  get 'buildings/index'


 #get 'buildings/index'

  namespace :admin do
    resources :buildings do
      resources :rooms
    end
    resources :lessons
    resources :courses
  end

  get 'admin' => 'admin/building#index'



  resources :buildings do
    resources :rooms, only: [:index, :new, :create, :edit, :update, :destroy, :show] do

      resources :lessons
    end

  end





  #root 'buildings#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/building.rb
class Building < ApplicationRecord
  has_many :rooms, dependent: :destroy
  validates :title, presence: true,
            length: { minimum: 5 }
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :teacher_assignments
  has_many :teachers, through: :teacher_assignments

  has_many :student_assignments
  has_many :students, through: :student_assignments

  has_many :lessons
  validates :title, presence: true

  extend Enumerize

  enumerize :language, in: { czech: 1, english: 2}, default: :czech
  enumerize :study_type, in: %w(full_time part_time), predicates: true

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :room
  belongs_to :teacher
  belongs_to :course

  validates :start_at, presence: true
  validates :end_at, presence: true

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :building, :foreign_key => 'building_id'
  has_many :lessons
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :student_assignments
  has_many :courses, through: :student_assignments

  extend Enumerize

  enumerize :study_type, in: %w(full_time part_time), predicates: true

  validates :first_name, presence: true,
            length: { maximum: 20 }

  validates :last_name, presence: true,
            length: { maximum: 20 }
end

app/models/student_assignment.rb
class StudentAssignment < ApplicationRecord
  belongs_to :course
  belongs_to :student
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :teacher_assignments
  has_many :courses, through: :teacher_assignments
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/teacher_assignment.rb
class TeacherAssignment < ApplicationRecord
  belongs_to :teacher
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/buildings_controller.rb
class Admin::BuildingsController < Admin::AdminController
  before_action :set_admin_building, only: [:show, :edit, :update, :destroy]

  # GET /admin/buildings
  # GET /admin/buildings.json
  def index
    @admin_buildings = Building.all
  end

  # GET /admin/buildings/1
  # GET /admin/buildings/1.json
  def show
  end

  # GET /admin/buildings/new
  def new
    @admin_building = Building.new
  end

  # GET /admin/buildings/1/edit
  def edit
  end


  # POST /admin/buildings
  # POST /admin/buildings.json
  def create
    @admin_building = Building.new(admin_building_params)

    respond_to do |format|
      if @admin_building.save
        format.html { redirect_to [:admin, @admin_building], notice: 'Building was successfully created.' }
        format.json { render :show, status: :created, location: @admin_building }
      else
        format.html { render :new }
        format.json { render json: @admin_building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/buildings/1
  # PATCH/PUT /admin/buildings/1.json
  def update
    respond_to do |format|
      if @admin_building.update(admin_building_params)
        format.html { redirect_to [:admin, @admin_building], notice: 'Building was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_building }
      else
        format.html { render :edit }
        format.json { render json: @admin_building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/buildings/1
  # DELETE /admin/buildings/1.json
  def destroy
    @admin_building.destroy
    respond_to do |format|
      format.html { redirect_to [:admin, admin_buildings_url], notice: 'Building was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_building
      @admin_building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_building_params
      params.require(:post).permit(:title, :code)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  #before_action :authenticate_user!
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController



  def index
    @buildings = Building.all
  end

  def show
    @building = Building.find(params[:id])
  end

  def new
    @building = Building.new
  end

  def edit
    @building = Building.find(params[:id])
  end

  def create
    @building = Building.new(building_params)

    if @building.save
      redirect_to @building
    else
      render 'new'
    end

  end


  def update
    @building = Building.find(params[:id])

    if @building.update(building_params)
      redirect_to @building
    else
      render 'edit'
    end
  end


  def destroy
    @building = Building.find(params[:id])

    @building.destroy

    redirect_to buildings_path
  end

  private
  def building_params
    params.require(:building).permit(:title, :code)
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show ]


  def index
    @courses = Course.all
  end


  def show
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :code, :study_type, :language)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  before_action :set_lesson, only: [:show]
  before_action :set_room


  def index
    @lessons = Lesson.all
  end

  def new
    @lesson = Lesson.new
  end


  def show
  end

  private
  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def lesson_params
    params.require(:lesson).permit(:start_at, :end_at, :duration)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :set_building
  before_action :set_room, only: [:show ]

  def create
    @building = Building.find(params[:building_id])
    @room = @building.rooms.create(room_params)
    redirect_to building_path(@building)
  end

  def new
    @room = Room.new(building_id: @building.id)
  end

  def show

  end


  def destroy
    @building = Building.find(params[:building_id])
    @room = @building.rooms.find(params[:id])
    @room.destroy
    redirect_to building_path(@building)
  end



  private
  def set_building
    @building = Building.find(params[:building_id])
  end

  def set_room
    @room = Room.find(params[:id])
  end



  def room_params
    params.require(:room).permit(:title, :code, :building_id)
  end
end

app/helpers/admin/buildings_helper.rb
module Admin::BuildingsHelper
end

app/helpers/admin/rooms_helper.rb
module Admin::RoomsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/admin/buildings/_form.html.erb
<%= simple_form_for(@admin_building) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/buildings/edit.html.erb
<h1>Editing Admin Building</h1>

<%= render 'form', admin_building: @admin_building %>

<%= link_to 'Show', @admin_building %> |
<%= link_to 'Back', admin_buildings_path %>

app/views/admin/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Administration Buildings</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_buildings.each do |admin_building| %>
      <tr>
        <td><%= link_to 'Show', admin_building %></td>
        <td><%= link_to 'Edit', edit_admin_building_path(admin_building) %></td>
        <td><%= link_to 'Destroy', admin_building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Building', new_admin_building_path %>

app/views/admin/buildings/new.html.erb
<h1>New Admin Building</h1>

<%= render 'form', admin_building: @admin_building %>

<%= link_to 'Back', admin_buildings_path %>

app/views/admin/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_building_path(@admin_building) %> |
<%= link_to 'Back', admin_buildings_path %>

app/views/buildings/_form.html.erb
<%= simple_form_for(@building) do |f| %>
    <%= f.input :title %>
    <%= f.input :code %>
    <%= f.button :submit %>
<% end %>

app/views/buildings/edit.html.erb
<h1>Edit buildings</h1>

<%= render 'form' %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<div class="container-fluid">
<h1>Listing Buildings</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Code</th>
    <th colspan="2"></th>
  </tr>

  <% @buildings.each do |building| %>
      <tr>
        <td><%= building.title %></td>
        <td><%= building.code %></td>
        <td><%= link_to 'Show', building_path(building) %></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
      </tr>
  <% end %>
</table>

<%= link_to 'New Building', new_building_path %>

</div>



<!--
fsdfdsfds
fdsfdsfd
-->

app/views/buildings/new.html.erb
<h1>New buildings</h1>

<%= render 'form' %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<div class="container-fluid">
  <p>
    <strong>Title:</strong>
    <%= @building.title %>
  </p>

  <p>
    <strong>Code:</strong>
    <%= @building.code %>
  </p>

  <h2>Rooms</h2>

  <%= render @building.rooms %>



  <%= link_to 'New room', new_building_room_path(building_id: @building.id) %>

<br />
  <br />



  <%= link_to 'Edit', edit_building_path(@building) %> |
  <%= link_to 'Delete',
              building_path(@building),
              method: :delete,
              data: { confirm: 'Jsi si jistý?' } %>  |
  <%= link_to 'Back', buildings_path %>

</div>