config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, path: 'admin', skip: :registrations

  devise_for :users

  get 'buildings/index'


 #get 'buildings/index'

  namespace :admin do
    resources :buildings do
      resources :rooms
    end
    resources :lessons
    resources :courses
  end

  get 'admin' => 'admin/building#index'



  resources :buildings do
    resources :rooms, only: [:index, :new, :create, :edit, :update, :destroy, :show] do

      resources :lessons
    end

  end





  #root 'buildings#index'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/building.rb
class Building < ApplicationRecord
  has_many :rooms, dependent: :destroy
  validates :title, presence: true,
            length: { minimum: 5 }
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :teacher_assignments
  has_many :teachers, through: :teacher_assignments

  has_many :student_assignments
  has_many :students, through: :student_assignments

  has_many :lessons
  validates :title, presence: true

  extend Enumerize

  enumerize :language, in: { czech: 1, english: 2}, default: :czech
  enumerize :study_type, in: %w(full_time part_time), predicates: true

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :room
  belongs_to :teacher
  belongs_to :course

  validates :start_at, presence: true
  validates :end_at, presence: true

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :building, :foreign_key => 'building_id'
  has_many :lessons
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :student_assignments
  has_many :courses, through: :student_assignments

  extend Enumerize

  enumerize :study_type, in: %w(full_time part_time), predicates: true

  validates :first_name, presence: true,
            length: { maximum: 20 }

  validates :last_name, presence: true,
            length: { maximum: 20 }
end

app/models/student_assignment.rb
class StudentAssignment < ApplicationRecord
  belongs_to :course
  belongs_to :student
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  has_many :teacher_assignments
  has_many :courses, through: :teacher_assignments
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/teacher_assignment.rb
class TeacherAssignment < ApplicationRecord
  belongs_to :teacher
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show ]


  def index
    @courses = Course.all
  end


  def show
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:title, :code, :study_type, :language)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

  before_action :set_lesson, only: [:show]
  before_action :set_room


  def index
    @lessons = Lesson.all
  end

  def new
    @lesson = Lesson.new
  end


  def show
  end

  private
  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def lesson_params
    params.require(:lesson).permit(:start_at, :end_at, :duration)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :set_building
  before_action :set_room, only: [:show ]

  def create
    @building = Building.find(params[:building_id])
    @room = @building.rooms.create(room_params)
    redirect_to building_path(@building)
  end

  def new
    @room = Room.new(building_id: @building.id)
  end

  def show

  end


  def destroy
    @building = Building.find(params[:building_id])
    @room = @building.rooms.find(params[:id])
    @room.destroy
    redirect_to building_path(@building)
  end



  private
  def set_building
    @building = Building.find(params[:building_id])
  end

  def set_room
    @room = Room.find(params[:id])
  end



  def room_params
    params.require(:room).permit(:title, :code, :building_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/_signin.html.erb
<p class="navbar-text pull-right">
  <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
      <%= link_to "Login", new_admin_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>

<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog Admin</title>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<%= render 'layouts/signin' %>


<div class="container">
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <%= value %>
      </div>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= render 'layouts/signin' %>


    <%= yield %>

  </body>
</html>